version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-spring-app
    env_file:
      - .env
    ports:
      - "9090:9090"
    depends_on:
      - postgres
